# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x06openai\"\x9b\x01\n\x0cLoginMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x13\n\x0bplatform_id\x18\x03 \x01(\t\x12\r\n\x05os_id\x18\x04 \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x05 \x01(\t\x12\x1a\n\x12\x63hallenge_response\x18\x06 \x01(\t\x12\x0f\n\x07payload\x18\x07 \x01(\t\"1\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\tInputData\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\"-\n\nOutputData\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t2w\n\x06OpenAi\x12\x36\n\x05Login\x12\x14.openai.LoginMessage\x1a\x15.openai.LoginResponse\"\x00\x12\x35\n\nTextToText\x12\x11.openai.InputData\x1a\x12.openai.OutputData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LOGINMESSAGE']._serialized_start=26
  _globals['_LOGINMESSAGE']._serialized_end=181
  _globals['_LOGINRESPONSE']._serialized_start=183
  _globals['_LOGINRESPONSE']._serialized_end=232
  _globals['_INPUTDATA']._serialized_start=234
  _globals['_INPUTDATA']._serialized_end=278
  _globals['_OUTPUTDATA']._serialized_start=280
  _globals['_OUTPUTDATA']._serialized_end=325
  _globals['_OPENAI']._serialized_start=327
  _globals['_OPENAI']._serialized_end=446
# @@protoc_insertion_point(module_scope)
